name: Install pyshell

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'
            cache: 'pip'
        
        - name: Build Boost
          uses: egor-tensin/build-boost@v1
          with:
            version: '1.77.0'
            libraries: filesystem program_options system

        - name: Setup cmake
          uses: jwlawson/actions-setup-cmake@v1.14

        - name: Install pyshell
          run: |
            git clone https://gitlab.com/numod/shell-energy.git
            cd shell-energy
            mkdir build
            cd build
            cmake -DBUILD_PYTHON=ON ..
            cmake --build . --config Release
            cd python
            cp *.so `python -m site --user-site`

        - name: Install requirements
          run: |
            pip install -r requirements.txt
            pip install .
        
        - name: Run tests
          run: pytest tests/

